name: "[builder] Build and Push"
# run every two hours to check for updates
on:
  workflow_dispatch:

env:
  TAG: "1.2.0"
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
  #PLATFORMS: "linux/amd64,linux/arm64"
  #PLATFORMS: "linux/amd64"

jobs:
  builder-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push - builder [debian]
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./debian/Dockerfile.builder
          platforms: ${{ env.PLATFORMS }}
          #   tiltedevolution-builder
          #     latest-debian
          #     {{ TAG }}-debian
          #   tiltedevolution-debian
          #     builder-debian
          #     builder-latest-debian
          #     builder-{{ TAG }}-debian
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-builder:latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution-builder:${{ env.TAG }}-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:builder-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:builder-latest-debian
            ${{ vars.DOCKERHUB_USERNAME }}/tiltedevolution:builder-${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-builder:latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution-builder:${{ env.TAG }}-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:builder-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:builder-latest-debian
            ghcr.io/${{ github.repository_owner }}/tiltedevolution:builder-${{ env.TAG }}-debian
